### PR TITLE
Wallpaper changer using python- Aditya Iyer

### PR DESCRIPTION
**Pull request by aiyer786**
Changes wallpaper at 9 PM

### CODE REVIEW

**Review by AayushDongre — CHANGES_REQUESTED** [review]
Looks very similar to #12 and #13 . Are you sure the code is not plagiarized?

**Comment by aiyer786** [comment]
It might even look similar to other codes, we all kind of studied from the
sources easily available on the internet. But I am sure I wrote the code
with my own research. I had no prior knowledge of the libraries I have used
in the code but I have researched, tried and tested the best versions. So I
am pretty sure I have not plagiarized it.

**Comment by AayushDongre** [comment]
>we all kind of studied from the sources easily available on the internet.

Fair point. But I find it hard to believe that everything down to the comments and variable names is the same.

**Comment by aiyer786** [comment]
Its okay if my submission is not considered,  I did the challenge as an
opportunity to learn and I have so I have nothing more to explain. Thanks for
bringing the changes to my notice. I would be more careful from the next
time and check with other people's codes maybe. Thank you for politely
pointing it out 😀. Looking forward to upcoming challenges 🙌

**Comment by aiyer786** [comment]
Also, compare the code with very initial pull requests too, you can find
many similarities, if you might have missed it because of recent pulls
being fresh in your memory!

**Comment by AayushDongre** [comment]
Alright cool. I'll look into how to avoid the problem of so many people having identical solutions in the coming challenges. Maybe having a bit non-linear challenges will do the trick! But to be fair to other people whose PRs didnt get merged, I'm going to have to close this for now.

However, you can feel free to reopen it anytime if you decide to make any changes!:v:

**Pull request closed without merging**
